### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by koboskom** [grzes5003/LicensePlateRec#1]
1. Niekompletny plik `requirements.txt` (numpy, cx_Freeze)
1. Nie działa na testowym nagraniu (błędne wyniki)
2. Bez wybrania filmu, przycisk "open video" otwiera explorator windows
3. Bez wybrania filmu, progres rozpoczyna się i rzuca wyjątkiem "PermissionError: [Errno 13] Permission denied: '/_log.log'"
    Podobie bez wybrania "destination directory" domyślnie log próbuje zostać zapisany w `/grupaA1_log.log` a nie ma uprawnień, skutkując tym samym wyjątkiem.
4. Bardzo często gdy zostanie wyrzucony wyjątek to proces nie zatrzymuje się pomimo zamknięcia okna
5. Pliki "preview" z miniaturkami tworzą się w katalogu z którego uruchamiana jest aplikacja natomiast wczytywane są z katalogu gui w katalogu projektu
6. Brak zabezpieczenia przed wielokrotnym wciśnięciem przycisku "start analize" ( w najgorszym wypadku np. po wciśnięciu go 3 razy przy odstępie 1 sekunda lub 2 razy w odstępie 5 sekund, program się zawiesza i nie da się go zamknąć)
Błąd:
```
22:54:05 - core.actorClasses.outputGenerator - Thread-32 - INFO - Writing logs to file
22:54:05 - core.actorClasses.outputGenerator - Thread-32 - INFO - Writing logs to file
22:54:05 - core.actorClasses.outputGenerator - Thread-32 - INFO - Writing logs to file
22:54:05 - core.actorClasses.outputGenerator - Thread-32 - INFO - Writing logs to file
22:54:05 - core.actorClasses.outputGenerator - Thread-32 - INFO - Writing logs to file
22:54:05 - core.actorClasses.outputGenerator - Thread-32 - INFO - Writing logs to file
22:54:05 - core.actorClasses.outputGenerator - Thread-32 - INFO - Writing logs to file
22:54:05 - core.actorClasses.outputGenerator - Thread-32 - INFO - Writing logs to file
22:54:05 - core.actorClasses.outputGenerator - Thread-32 - INFO - Writing logs to file
22:54:05 - core.actorClasses.outputGenerator - Thread-32 - INFO - Writing logs to file
22:54:05 - core.actorClasses.outputGenerator - Thread-32 - INFO - Writing logs to file
INFO:core.actorClasses.outputGenerator:Writing logs to file
Exception in thread Thread-32:
Traceback (most recent call last):
  File "C:\Users\Ola Siwak\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Ola Siwak\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Ola Siwak\IO\LicensePlateRec\core\manager\Manager.py", line 120, in _collect_img_processing
    self._analysed_frames.on_completed()
  File "C:\Users\Ola Siwak\AppData\Local\Programs\Python\Python39\lib\site-packages\rx\subject\subject.py", line 89, in on_completed
    super().on_completed()
  File "C:\Users\Ola Siwak\AppData\Local\Programs\Python\Python39\lib\site-packages\rx\core\observer\observer.py", line 56, in on_completed
    self._on_completed_core()
  File "C:\Users\Ola Siwak\AppData\Local\Programs\Python\Python39\lib\site-packages\rx\subject\subject.py", line 97, in _on_completed_core
    observer.on_completed()
  File "C:\Users\Ola Siwak\AppData\Local\Programs\Python\Python39\lib\site-packages\rx\core\observer\autodetachobserver.py", line 44, in on_completed
    self._on_completed()
  File "C:\Users\Ola Siwak\IO\LicensePlateRec\core\actorClasses\outputGenerator.py", line 41, in <lambda>
    on_completed=lambda: self._on_completed()
  File "C:\Users\Ola Siwak\IO\LicensePlateRec\core\actorClasses\outputGenerator.py", line 52, in _on_completed
    _y, _x, _ = self._logs[1].img_.shape
KeyError: 1
```

7. Przy uruchamianiu wersji konsolowej wyświetla się informacja o istnieniu flagi `--help` a po jej zastosowaniu dowiadujemy się zaledwie że istnieje flaga `--help` xD
8. Nie da się uruchomić wersji standalone.
Komenda: `python mainCore.py ../grupaA1.mp4 ../output config.toml`
Wynik:
```
23:15:53|Thread-1|core.manager.Manager|114|ERROR|cannot schedule new futures after interpreter shutdown
23:15:53 - core.actorClasses.outputGenerator - Thread-1 - INFO - Writing logs to file
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Ola Siwak\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Ola Siwak\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Ola Siwak\IO\LicensePlateRec\core\manager\Manager.py", line 120, in _collect_img_processing
    self._analysed_frames.on_completed()
  File "C:\Users\Ola Siwak\AppData\Local\Programs\Python\Python39\lib\site-packages\rx\subject\subject.py", line 89, in on_completed
    super().on_completed()
  File "C:\Users\Ola Siwak\AppData\Local\Programs\Python\Python39\lib\site-packages\rx\core\observer\observer.py", line 56, in on_completed
    self._on_completed_core()
  File "C:\Users\Ola Siwak\AppData\Local\Programs\Python\Python39\lib\site-packages\rx\subject\subject.py", line 97, in _on_completed_core
    observer.on_completed()
  File "C:\Users\Ola Siwak\AppData\Local\Programs\Python\Python39\lib\site-packages\rx\core\observer\autodetachobserver.py", line 44, in on_completed
    self._on_completed()
  File "C:\Users\Ola Siwak\IO\LicensePlateRec\core\actorClasses\outputGenerator.py", line 41, in <lambda>
    on_completed=lambda: self._on_completed()
  File "C:\Users\Ola Siwak\IO\LicensePlateRec\core\actorClasses\outputGenerator.py", line 52, in _on_completed
    _y, _x, _ = self._logs[1].img_.shape
KeyError: 1
```
9. Brak wsparcia dla znaków utf-8 w nazwie. Gdy w nazwie pliku znajdzie się np. znak `é` to nie jest aktualizowana nazwa w GUI.
10. Podczas przetwarzania filmu klatki są usuwane z pamięci dopiero po zakończeniu przetważania, przez co podczas przetważania dużego pliku program wykorzystał całe 24G ramu

**Comment by grzes5003** [comment]
## Naprawione 

> 1. Niekompletny plik requirements.txt

> 3. Bez wybrania filmu, przycisk "open video" otwiera explorator windows

> 4. Bez wybrania filmu, progres rozpoczyna się i rzuca wyjątkiem "PermissionError: [Errno 13] Permission denied: '/_log.log'"

> 6. Pliki "preview" z miniaturkami tworzą się w katalogu z którego uruchamiana jest aplikacja natomiast wczytywane są z katalogu gui w katalogu projektu

> 7. Brak zabezpieczenia przed wielokrotnym wciśnięciem przycisku "start analize"
-----
## Zostanie potencjalnie naprawione w przyszłości

> 2. Nie działa na testowym nagraniu (błędne wyniki) 

Wyniki bardzo zależą od typu i jakości nagrania

> 10. Podczas przetwarzania filmu klatki są usuwane z pamięci dopiero po zakończeniu przetważania, przez co podczas przetważania dużego pliku program wykorzystał całe 24G ramu

Problem jest trudniejszy do rozwiązania niż na początku myślałem.


>5. Bardzo często gdy zostanie wyrzucony wyjątek to proces nie zatrzymuje się pomimo zamknięcia okna

W tej wersji programu dużo trudniej doprowadzić do wyjątku

----
## Nie zostanie naprawione

> 8. Nie da się uruchomić wersji standalone.
Komenda: python mainCore.py ../grupaA1.mp4 ../output config.toml

"u mnie działa" + nie jest to funkcjonalność związana z końcowym produktem

> 9. Brak wsparcia dla znaków utf-8 w nazwie. Gdy w nazwie pliku znajdzie się np. znak é to nie jest aktualizowana nazwa w GUI.

Nie jest to sprecyzowane w Inż wymagań, a sam fix nie jest tak oczywisty jak się może wydawać
